# Generated by Django 5.0.6 on 2024-06-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spec',
            name='var_type',
            field=models.CharField(blank=True, choices=[('int', 'Целое число'), ('str', 'Строка'), ('float', 'Десятичная дробь'), ('bool', 'Да/Нет')], max_length=50, null=True, verbose_name='Тип значения'),
        ),
    ]
