# Generated by Django 5.0.6 on 2024-06-24 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0002_alter_spec_var_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specunitvalidation',
            options={'verbose_name': 'Валидация единицы измерения товара', 'verbose_name_plural': 'Валидации единиц измерения товаров'},
        ),
        migrations.AlterField(
            model_name='searchfiltertype',
            name='key',
            field=models.CharField(choices=[('checkbox', 'Чекбокс')], default='checkbox', max_length=50, verbose_name='Ключ поиска'),
        ),
        migrations.AlterField(
            model_name='spec',
            name='var_type',
            field=models.CharField(blank=True, choices=[('int', 'Целое число'), ('str', 'Строка'), ('float', 'Десятичная дробь')], max_length=50, null=True, verbose_name='Тип значения'),
        ),
        migrations.AlterField(
            model_name='specunitvalidation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя единицы измерения для валидации'),
        ),
        migrations.AlterField(
            model_name='specunitvalidation',
            name='specunit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specs.specunit', verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='specunitvalidation',
            name='var_type',
            field=models.CharField(choices=[('int', 'Целое число'), ('str', 'Строка'), ('float', 'Десятичная дробь'), ('bool', 'Да/Нет')], max_length=50, verbose_name='Тип значения'),
        ),
    ]
