# Generated by Django 5.0.6 on 2024-06-20 21:45

import utils.image_uploaders
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=utils.image_uploaders.product_image_uploader, verbose_name='Изображение товара'),
        ),
    ]
