# Generated by Django 5.0.6 on 2024-06-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='items_of_cart', to='main.cartitem', verbose_name='Товары'),
        ),
    ]
