# Generated by Django 5.0.6 on 2024-06-24 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_cart_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='commit',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_data',
            new_name='order_date',
        ),
    ]
